batch_size: 
num_epochs: 
patience: 
learning_rate: 

img_size_in: 
img_size_out: 
patch_size: 
in_chans: 
out_chans: 
embed_dim: 
tokens_mlp_dim: 
channels_mlp_dim: 
num_blocks: 
f_hidden: 
drop_rate: 

early_stop_flag: 

model_module: 
model_class: 

data_path: 
mask_path: 
checkpoint_path: 